<?php

if (!function_exists('lorem'))
{
	function lorem($numberOfWords = 50)
	{
		$words = "Bacon ipsum dolor amet meatball tenderloin bresaola doner landjaeger salami rump boudin jowl shoulder drumstick pancetta shankle spare ribs. Kevin short loin corned beef hamburger jerky shank. Prosciutto turkey shoulder, jowl ham ribeye shankle pork beef ribs tri-tip. Boudin tri-tip salami, rump bacon short loin leberkas andouille. Kielbasa beef meatloaf capicola cow bresaola. Shankle ribeye pork chop, brisket chuck biltong kevin pork salami filet mignon short loin picanha. Shoulder strip steak filet mignon andouille, leberkas pork loin shank pork chop pastrami doner. Ground round bacon short ribs beef ribs landjaeger ham hock. Landjaeger pork belly ground round salami, chuck tail jowl capicola strip steak tri-tip. Ball tip fatback tri-tip leberkas. Shoulder jowl sausage tongue, fatback jerky ham hock brisket. Strip steak short loin tongue ribeye picanha tenderloin beef ribs cow shoulder porchetta jerky drumstick pig. Filet mignon picanha alcatra short ribs tail corned beef swine. Flank tri-tip meatball fatback, bacon chicken strip steak hamburger prosciutto brisket cupim. Ham frankfurter meatloaf, corned beef meatball leberkas ball tip. Doner filet mignon bacon, pig frankfurter biltong hamburger jerky rump meatball picanha porchetta meatloaf chuck. Landjaeger sirloin pancetta ball tip beef ribs t-bone brisket strip steak chicken drumstick ham filet mignon rump ribeye. Tenderloin ground round drumstick, pastrami tongue jowl ham hock picanha spare ribs boudin ribeye. Salami ribeye boudin chicken. Turkey picanha ham hock frankfurter, biltong meatball flank porchetta kevin andouille doner strip steak pork loin. Chuck flank brisket rump leberkas, corned beef filet mignon turducken cupim short ribs doner tail salami biltong. Flank alcatra chicken, biltong meatloaf tri-tip andouille tongue brisket. Swine chuck capicola, landjaeger";

		return implode(' ', array_slice(explode(' ', $words), 0, $numberOfWords));
	}
}