<?php

class BrewersSeeder extends DatabaseSeeder {

	private $brewers = [
		"Aardwolf Brewery",
		"Agassiz Brewing",
		"Alaskan Brewing Company",
		"Alchemist Brewery",
		"AleSmith Brewing Company",
		"Allagash Brewing Company",
		"Amsterdam Brewing Company",
		"Anderson Valley Brewing Company ",
		"Arcadia Brewing Company",
		"Argus Brewer",
		"Badger Hill Brewing Co.",
		"Bad Tattoo Brewing Company ",
		"La Barberie",
		"Barkerville Brewing Co.",
		"Bayern Brewing, Inc. ",
		"Bear Republic Brewing Company",
		"Beau's All Natural Brewing Company ",
		"Belgh Brasse",
		"Bell's Brewery",
		"Big Al Brewing ",
		"BJ's Restaurant &amp; Brewery ",
		"Black Kettle Brewing Company ",
		"Blue Hills Brewery ",
		"Bold City Brewery ",
		"Bomber Brewing ",
		"Bootleg Brewery",
		"Boulder Beer Company",
		"Bluegrass Brewing Company",
		"Blue Point Brewing Company",
		"Bluetongue Brewery",
		"Boston Beer Company",
		"Boundary Bay Brewing Company",
		"Les Brasseurs du Nord",
		"BrewDog",
		"Brew Keeper",
		"Brewery Ommegang",
		"Brick Brewing Company",
		"BridgePort Brewing Company",
		"Brooklyn Brewery",
		"Buffalo Bill's Brewery",
		"Burleigh Brewing Company",
		"Cache Valley Brewing Company",
		"Calfkiller Brewing Company ",
		"Cameron's Brewing Company",
		"Canuck Empire Brewing ",
		"Capital Brewery",
		"Carillon Brewing Company",
		"Cascade Lakes Brewing Company ",
		"Casco Bay Brewing Co.",
		"Chew Valley Brewery ",
		"Christian Moerlein Brewing Co.",
		"The Church Brew Works",
		"Churchkey Can Company",
		"Cigar City Brewing",
		"Coastal Extreme Brewing Company",
		"Colonial Brewing Company",
		"Columbus Brewing Company",
		"Copper Kettle Brewing Company ",
		"Creemore Springs ",
		"Cricket Hill",
		"Cropton Brewery ",
		"Dageraad Brewing ",
		"Dark Horse Brewery",
		"The Dayton Beer Company ",
		"Desert Eagle ",
		"Devils Backbone Brewing Company",
		"Diamond Knot Brewing Company",
		"Dixie Brewing Company",
		"Doan’s Craft Brewing Company ",
		"Dogfish Head",
		"Dogwood Brewing ",
		"Dow Breweries",
		"Dragonmead",
		"Dugges Ale och Porterbryggeri",
		"Eden Brewery St Andrews",
		"Eel River Brewing Company",
		"Ellis Island Casino &amp; Brewery",
		"Empyrean Brewing Company",
		"Engine 15 Brewing Co.",
		"Fat Head's Brewery",
		"Feral Brewing Company",
		"F&amp;M Brewery",
		"Firestone Walker Brewing Company",
		"Fish Brewing Company",
		"Flying Bison Brewing Company",
		"Flying Dog Brewery",
		"Fort Garry Brewing Company",
		"Fóti Craft Brewery",
		"Four Mile Brewing Co.",
		"Founders Brewing Company",
		"Franconia Brewing Company",
		"Free State Brewery",
		"Fremont Brewin",
		"The entrance to Georgetown Brewing Company",
		"Gage Roads Brewing Company",
		"Georgetown Brewing Company",
		"Golan Brewery",
		"Gordon Biersch Brewing Company",
		"Granville Island Brewing",
		"Great Basin Brewing Company",
		"Great Lakes Brewing Company",
		"Great Western Brewing Company",
		"Greenbush Brewing Company",
		"Green Flash Brewing Company",
		"Green Leaf Brewing Co.",
		"Gritty McDuff's Brewing Company",
		"Gunbarrel Brewing Company ",
		"Hair of the Dog Brewing Company",
		"Hale's Ales",
		"Half Acre Beer Company",
		"Half Pints Brewing Company",
		"Hamburger Mary's",
		"Harpoon Brewery",
		"Hawaii Nui Brewing Company",
		"Heartland Brewery",
		"Heiner Brau",
		"High Point Brewing Company",
		"Hilliard's Beer",
		"Hogs Back Brewery",
		"Holgate Brewhouse",
		"Holy Cow Casino and Brewery",
		"Ice Harbor Brewing Company",
		"Intuition Ale Works ",
		"Jackie O's",
		"Jarrow Brewing Company",
		"Jolly Pumpkin Artisan Ales",
		"Kichesippi Beer Co.",
		"King Brewery",
		"Kingdom Breweries",
		"Kona Brewing Company",
		"Lacons Brewery",
		"Lagunitas Brewing Company",
		"Lakefront Brewery, Inc.",
		"Lakeport Brewing Company",
		"Laughing Dog Brewing",
		"List of New York breweries",
		"Little Creatures Brewery",
		"Lobethal Bierhaus",
		"London Fields Brewery",
		"Lone Tree Brewery",
		"Long Trail Brewing Company",
		"Lost Coast Brewery",
		"Lost Rhino Brewing Company",
		"Lumber Yard Brewing Co ",
		"MacTarnahan's Brewing Company",
		"Mad River Brewing Company",
		"Main Street Brewing Company ",
		"Main Street Station Hotel and Casino and Brewery",
		"Magic Hat Brewing Company",
		"Malt Shovel Brewery",
		"Marshall Brewing Company",
		"Matilda Bay Brewing Company",
		"Matt Brewing Company",
		"McAuslan Brewing",
		"McMenamins",
		"Mendocino Brewing Company",
		"Metropolitan Brewing",
		"Michigan Brewing Company",
		"Midnight Sun Brewing Company",
		"Mikkeller",
		"Mill Street Brewery",
		"Mount Hope Estate",
		"Mt. Begbie Brewing Company",
		"Mt. Shasta Brewing Company",
		"Muskoka Cottage Brewery",
		"Nail Brewing",
		"Nelson Brewing Company",
		"Newburyport Brewing Company",
		"New Orleans Lager and Ale Brewing Company",
		"North Coast Brewing Company",
		"Part of Otter Creek Brewing's production line",
		"Off Color Brewing",
		"Off the Rail Brewing",
		"Otter Creek Brewing",
		"Paddock Wood Brewing Company",
		"Penn Brewery",
		"Penpont Brewery",
		"Pipeworks Brewing ",
		"Port City Brewing Company",
		"Primo Brewing &amp; Malting Company",
		"Pyramid Breweries",
		"Quidi Vidi Brewing Company",
		"Rahr and Sons Brewing Company",
		"The Rare Barrel",
		"Real Ale Brewing Company",
		"Rebellion Beer Company",
		"Red Oak (beer)",
		"Revolution Brewing",
		"Rhodell Brewery",
		"Rivertown Brewing Company",
		"RJ Rockers Brewing Company",
		"Rock Art Brewery ",
		"Rock Bottom Restaurants",
		"Rogue Ales",
		"Rohrbach Brewing Company",
		"Rossland Beer Company ",
		"Rough Draft Brewing Company ",
		"Russell Brewing Company",
		"Russian River Brewing Company",
		"Steam Whistle Brewing",
		"Beers of Stone Brewing Company",
		"Saint Arnold Brewing Company",
		"Saint Louis Brewery",
		"San Francisco Brewing Company",
		"Santa Fe Brewing Company",
		"Sea Dog Brewing Company",
		"Shipyard Brewing Company",
		"Shmaltz Brewing Company",
		"Sierra Nevada Brewing Company",
		"Silver Gulch Brewing &amp; Bottling Company",
		"Six Rivers Brewery",
		"Sixpoint Craft Ales ",
		"SKA Brewing",
		"Skeena Brewing Company ",
		"Smuttynose Brewing Company",
		"Southern Star Brewing Company",
		"Speakeasy Ales and Lagers",
		"Sprecher Brewery",
		"Springfield Brewing Company",
		"St Arnou",
		"Steel &amp; Oak Brewing Co.",
		"Steel Toad Brewing Company ",
		"Steam Whistle Brewing",
		"Steelback Brewery",
		"Surly Brewing ",
		"Tallgrass Brewing Co",
		"Third Street Aleworks",
		"Thirsty Dog Brewing Company",
		"Three Floyds Brewing",
		"Tired Hands Brewing Company",
		"Tring Brewery",
		"Trouble Brewing (brewery)",
		"Trout River Brewing",
		"Tuckerman Brewing Company",
		"Two Brothers Brewing",
		"Upland Brewing Company",
		"Upper Canada Brewing Company",
		"Upslope Brewing Company",
		"Victory Brewing Company",
		"Wellington Brewery in Guelph, Ontario",
		"Walkerville Brewing Company",
		"War Horse Brewing Company",
		"Wellington Brewery",
		"Wet 'N Reckless Brewing Company – San Diego, California ",
		"Weyerbacher Brewing Company",
		"Wheelhouse Brewing Company ",
		"White Marsh Brewing Company",
		"White Rock Beach Beer Company ",
		"Whitewater Brewery",
		"Widmer Brothers Brewery",
		"Wild Rose Brewery ",
		"Williamsburg AleWerks",
		"XT Brewing Company",
		"Yards Brewing Company",
		"Yazoo Brewing Company",
		"Yellow Dog Brewing Co.",
		"Yukon Brewing Company",
	];

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$faker = $this->faker();

		foreach ($this->brewers as $brewer)
		{
			$found = DB::table('brewers')->where('name', '=', $brewer)->first();

			if (!$found)
			{
				DB::table('brewers')->insert([
					'address' => $faker->address,
					'description' => $faker->text,
					'name' => $brewer,
					'website' => $faker->url,
					'created_at' => new DateTime,
					'updated_at' => new DateTime,
				]);
			}
		}
	}
}